server:
  port: 8080  # Gateway server port

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**

        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/customers/**
            
management:
  endpoints:
    web:
      exposure:
        include: "*"
