INSERT INTO customer (name, phone) VALUES ('Alice Johnson', '555-6955');
INSERT INTO customer (name, phone) VALUES ('John Smith', '555-1742');
INSERT INTO customer (name, phone) VALUES ('Charlie Brown', '555-2382');
INSERT INTO customer (name, phone) VALUES ('John Brown', '555-8555');
INSERT INTO customer (name, phone) VALUES ('Charlie Johnson', '555-6147');
INSERT INTO customer (name, phone) VALUES ('Alice Davis', '555-9267');
INSERT INTO customer (name, phone) VALUES ('Alice Smith', '555-6139');
INSERT INTO customer (name, phone) VALUES ('John Smith', '555-4367');
INSERT INTO customer (name, phone) VALUES ('Jane Davis', '555-5787');
INSERT INTO customer (name, phone) VALUES ('Charlie Brown', '555-3591');
INSERT INTO cashier (name) VALUES ('Jane Johnson');
INSERT INTO cashier (name) VALUES ('Jane Doe');
INSERT INTO cashier (name) VALUES ('Jane Johnson');
INSERT INTO cashier (name) VALUES ('Jane Doe');
INSERT INTO cashier (name) VALUES ('Bob Smith');
INSERT INTO product (name, price) VALUES ('Product 1', 52.78);
INSERT INTO product (name, price) VALUES ('Product 2', 9.04);
INSERT INTO product (name, price) VALUES ('Product 3', 33.77);
INSERT INTO product (name, price) VALUES ('Product 4', 39.42);
INSERT INTO product (name, price) VALUES ('Product 5', 75.24);
INSERT INTO product (name, price) VALUES ('Product 6', 54.79);
INSERT INTO product (name, price) VALUES ('Product 7', 56.86);
INSERT INTO product (name, price) VALUES ('Product 8', 51.89);
INSERT INTO product (name, price) VALUES ('Product 9', 58.57);
INSERT INTO product (name, price) VALUES ('Product 10', 62.78);
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (9, 5, '2022-06-28 04:49:00.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (7, 1, '2024-07-08 23:18:35.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (3, 1, '2024-03-10 05:39:16.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (5, 3, '2022-04-05 16:00:32.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (5, 5, '2023-02-15 06:51:57.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (8, 2, '2023-07-17 12:36:54.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (6, 2, '2023-02-17 02:50:30.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (6, 3, '2024-01-02 11:35:13.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (3, 1, '2022-09-22 03:04:37.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (7, 4, '2023-06-28 09:07:19.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (7, 4, '2022-05-22 12:02:28.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (5, 4, '2022-04-11 08:22:51.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (6, 4, '2023-11-09 00:16:42.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (2, 1, '2022-02-04 02:41:50.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (5, 3, '2024-07-20 00:15:49.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (10, 2, '2024-10-11 19:50:18.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (5, 1, '2022-04-08 08:56:12.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (3, 2, '2022-10-21 13:00:56.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (9, 3, '2023-01-13 09:50:26.0');
INSERT INTO invoice (customer_id, cashier_id, created_date) VALUES (2, 3, '2024-01-14 17:17:41.0');
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (6, 1, 67.26, 3);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (9, 4, 21.36, 3);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (10, 4, 24.13, 1);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (10, 2, 62.68, 4);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (4, 4, 95.62, 9);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (10, 7, 6.43, 6);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (1, 1, 24.04, 7);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (6, 1, 99.73, 16);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (7, 8, 73.67, 13);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (10, 9, 54.71, 16);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (1, 2, 67.64, 1);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (8, 4, 36.59, 7);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (4, 1, 18.66, 10);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (10, 7, 45.15, 6);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (2, 4, 28.32, 15);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (9, 3, 46.19, 8);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (2, 4, 67.67, 3);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (5, 3, 79.36, 13);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (2, 3, 88.85, 8);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (3, 4, 85.34, 16);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (4, 3, 11.01, 19);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (10, 3, 6.74, 14);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (1, 1, 18.56, 17);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (7, 5, 15.71, 15);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (3, 9, 75.29, 7);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (1, 1, 78.00, 10);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (6, 3, 51.36, 12);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (4, 1, 64.41, 16);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (6, 2, 12.22, 18);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (5, 8, 8.80, 14);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (1, 8, 69.63, 20);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (10, 6, 99.44, 6);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (8, 9, 80.65, 4);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (1, 5, 62.13, 6);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (10, 5, 7.07, 10);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (6, 4, 36.08, 2);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (8, 8, 63.33, 3);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (6, 6, 9.51, 15);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (9, 6, 84.58, 5);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (6, 4, 52.60, 10);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (8, 3, 23.14, 11);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (4, 5, 20.84, 11);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (7, 8, 9.81, 15);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (9, 4, 45.55, 11);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (1, 8, 79.98, 2);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (4, 1, 24.76, 20);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (10, 10, 89.12, 19);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (3, 10, 12.46, 10);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (8, 8, 81.14, 7);
INSERT INTO invoice_detail (quantity, product_id, product_price, invoice_id) VALUES (9, 7, 73.03, 1);
